app = 'chatgpt2api'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5005
  force_https          = true
  auto_start_machines  = true
  auto_stop_machines   = false
  min_machines_running = 1
  processes            = ["app"]

  [http_service.concurrency]
    type       = "requests"
    soft_limit = 9999
    hard_limit = 9999

[mounts]
  source = "data"
  destination = "/app/data"
